name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    name: Test
    runs-on: ${{ matrix.platform }}
    env:
      RUST_I18N_DEBUG: 0
    steps:
      - uses: actions/checkout@v3
      - name: Setup | Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-test-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: make test
